# Generated by Django 5.2.17 on 2026-08-15 19:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='personas.sucursal')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('nombre_corto', models.CharField(max_length=24)),
                ('destino_impresion', models.CharField(choices=[('cocina', 'Cocina'), ('barra', 'Barra'), ('caja', 'Caja')], default='cocina', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('origen', models.CharField(default='menu_2026', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='personas.sucursal')),
            ],
            options={
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='personas.sucursal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.producto')),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nombre'), name='categoria_unica_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='producto_codigo_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='precio',
            constraint=models.UniqueConstraint(fields=('sucursal', 'producto', 'vigente_desde'), name='precio_unico_vigencia'),
        ),
    ]
