# Generated by Django 5.2.17 on 2026-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='abreviaturas_termino',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='producto',
            name='permite_termino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='termino_predeterminado',
            field=models.CharField(blank=True, choices=[('dorado', 'Dorado'), ('medio', 'Medio'), ('blando', 'Blando')], max_length=8),
        ),
    ]
