# Generated by Django 5.2.17 on 2026-09-24 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_producto_imagen'),
        ('personas', '0006_usuariopos_es_sistema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadCategoriaCentral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('central_id', models.UUIDField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identidad_central', to='catalogo.categoria')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_centrales', to='personas.sucursal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'central_id'), name='categoria_central_unica_sucursal')],
            },
        ),
        migrations.CreateModel(
            name='IdentidadProductoCentral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('central_id', models.UUIDField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identidad_central', to='catalogo.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_centrales', to='personas.sucursal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'central_id'), name='producto_central_unico_sucursal')],
            },
        ),
        migrations.CreateModel(
            name='PublicacionCatalogoCentral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_id', models.UUIDField()),
                ('version', models.PositiveIntegerField()),
                ('version_contrato', models.PositiveSmallIntegerField(default=2)),
                ('checksum', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('aplicada', 'Aplicada'), ('rechazada', 'Rechazada')], max_length=12)),
                ('snapshot', models.JSONField(default=dict)),
                ('codigo_error', models.CharField(blank=True, max_length=40)),
                ('detalle_seguro', models.CharField(blank=True, max_length=240)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones_catalogo', to='personas.sucursal')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'release_id'), name='catalogo_release_unico_sucursal'), models.UniqueConstraint(fields=('sucursal', 'version'), name='catalogo_version_unica_sucursal')],
            },
        ),
    ]
