# Generated by Django 5.2.17 on 2026-09-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_identidadcategoriacentral_identidadproductocentral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='origen',
            field=models.CharField(default='local', max_length=30),
        ),
        migrations.AddField(
            model_name='precio',
            name='publicacion_central_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
