# Generated by Django 5.2.17 on 2026-09-25 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_publicacioncatalogocentral_identidades'),
        ('personas', '0007_production_capacidades_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible_sucursal',
            field=models.BooleanField(default=True, help_text='Disponibilidad local publicada por Central; se conserva el producto histórico.'),
        ),
        migrations.CreateModel(
            name='EstadoAprovisionamientoCatalogo',
            fields=[
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='estado_aprovisionamiento_catalogo', serialize=False, to='personas.sucursal')),
                ('estado', models.CharField(choices=[('enrolado', 'Enrolado'), ('esperando_catalogo_inicial', 'Esperando catálogo inicial'), ('catalogo_aplicado', 'Catálogo aplicado'), ('listo', 'Listo')], default='enrolado', max_length=30)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados_aprovisionamiento', to='catalogo.publicacioncatalogocentral')),
            ],
        ),
    ]
