# Generated by Django 5.2.17 on 2026-08-15 19:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('domicilio', models.TextField(blank=True)),
                ('colonia', models.CharField(blank=True, max_length=120)),
                ('referencia', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='personas.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('comedor', 'Comedor'), ('domicilio', 'Domicilio'), ('sucursales', 'Sucursales')], max_length=15)),
                ('clave', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='personas.sucursal')),
            ],
            options={
                'ordering': ['canal', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.PositiveIntegerField()),
                ('canal', models.CharField(choices=[('comedor', 'Comedor'), ('domicilio', 'Domicilio'), ('sucursales', 'Sucursales')], max_length=15)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('procesado', 'Procesado'), ('cobrar', 'Por cobrar'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='abierto', max_length=15)),
                ('comentario_general', models.TextField(blank=True)),
                ('entrega_aproximada', models.TimeField(blank=True, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=12)),
                ('importe_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('atendio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='personas.usuariopos')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ventas.cliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ventas.mesa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='personas.sucursal')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comensal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_producto', models.CharField(max_length=180)),
                ('nombre_corto', models.CharField(max_length=24)),
                ('comentario', models.CharField(blank=True, max_length=220)),
                ('procesada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='catalogo.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='personas.sucursal')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='ventas.ticket')),
            ],
            options={
                'ordering': ['creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ModificadorTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comensal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificadores_ticket', to='personas.sucursal')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificadores', to='ventas.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='EventoOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agregado', models.CharField(max_length=40)),
                ('agregado_id', models.UUIDField()),
                ('tipo', models.CharField(max_length=80)),
                ('datos', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_outbox', to='personas.sucursal')),
            ],
            options={
                'ordering': ['creado_en'],
                'indexes': [models.Index(fields=['publicado_en', 'creado_en'], name='ventas_even_publica_00b665_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.UniqueConstraint(fields=('sucursal', 'clave'), name='mesa_clave_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('sucursal', 'folio'), name='ticket_folio_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='modificadorticket',
            constraint=models.UniqueConstraint(fields=('ticket', 'comensal', 'codigo'), name='modificador_unico_comensal'),
        ),
    ]
