# Generated by Django 5.2.17 on 2026-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_modificadorticket_comensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='termino',
            field=models.CharField(blank=True, choices=[('dorado', 'Dorado'), ('medio', 'Medio'), ('blando', 'Blando')], max_length=8),
        ),
    ]
