# Generated by Django 5.2.17 on 2026-08-24 17:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_producto_options'),
        ('personas', '0001_initial'),
        ('ventas', '0009_tipos_servicio_y_pedidos_por_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen_id', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('sucursal', 'Sucursal'), ('cliente_mayorista', 'Cliente mayorista')], max_length=24)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='partida',
            name='cantidad_por_precio',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8),
        ),
        migrations.AddField(
            model_name='partida',
            name='unidad',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='partida',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='catalogo.producto'),
        ),
        migrations.CreateModel(
            name='ProductoSucursal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen_id', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_ticket', models.CharField(max_length=40)),
                ('unidad', models.CharField(default='PZA', max_length=8)),
                ('cantidad_por_precio', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_sucursales', to='personas.sucursal')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioProductoSucursal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_ticket', models.CharField(max_length=40)),
                ('vigente_desde', models.DateField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_productos_sucursales', to='personas.sucursal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='ventas.productosucursal')),
            ],
            options={
                'ordering': ['producto__orden', '-vigente_desde'],
            },
        ),
        migrations.AddField(
            model_name='partida',
            name='producto_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='ventas.productosucursal'),
        ),
        migrations.AddConstraint(
            model_name='partida',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('producto__isnull', False), ('producto_sucursal__isnull', True)), models.Q(('producto__isnull', True), ('producto_sucursal__isnull', False)), _connector='OR'), name='partida_un_solo_catalogo'),
        ),
        migrations.AddField(
            model_name='sucursalpedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_sucursales', to='personas.sucursal'),
        ),
        migrations.AddField(
            model_name='precioproductosucursal',
            name='cliente_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='ventas.sucursalpedido'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='cliente_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posiciones', to='ventas.sucursalpedido'),
        ),
        migrations.AddConstraint(
            model_name='productosucursal',
            constraint=models.UniqueConstraint(fields=('sucursal', 'origen_id'), name='producto_sucursal_origen_unico'),
        ),
        migrations.AddConstraint(
            model_name='sucursalpedido',
            constraint=models.UniqueConstraint(fields=('sucursal', 'origen_id'), name='sucursal_pedido_origen_unico'),
        ),
        migrations.AddConstraint(
            model_name='precioproductosucursal',
            constraint=models.UniqueConstraint(fields=('cliente_sucursal', 'producto', 'vigente_desde'), name='precio_producto_sucursal_fecha_unico'),
        ),
    ]
