# Generated by Django 5.2.17 on 2026-08-24 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('ventas', '0010_sucursalpedido_partida_cantidad_por_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoSucursalImportado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen', models.CharField(default='pedidos_sucursales_sqlite', max_length=40)),
                ('origen_id', models.PositiveIntegerField()),
                ('codigo_publico', models.CharField(blank=True, max_length=40)),
                ('estado_origen', models.CharField(blank=True, max_length=16)),
                ('importado_en', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_sucursal_importados', to='personas.sucursal')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='importacion_sucursal', to='ventas.ticket')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'origen', 'origen_id'), name='pedido_sucursal_importado_unico')],
            },
        ),
    ]
