# Generated by Django 5.2.17 on 2026-08-29 01:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_remove_usuariopos_usuario_clave_sucursal_rol_tipo_and_more'),
        ('ventas', '0011_pedidosucursalimportado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSucursal',
            fields=[
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='configuracion_pos', serialize=False, to='personas.sucursal')),
                ('clave_administrador', models.CharField(max_length=128)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('totales_canales', models.JSONField(default=dict)),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_entradas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_salidas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_caja', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fin'],
            },
        ),
        migrations.CreateModel(
            name='CorteSucursal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partidas', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionRepartidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fondo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_efectivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_terminal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pedidos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_a_entregar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=8)),
                ('concepto', models.CharField(max_length=180)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReporteAdministrativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('liquidacion', 'Total de repartidor'), ('parcial', 'Reporte parcial'), ('corte_caja', 'Corte de caja'), ('corte_sucursal', 'Corte de sucursal')], max_length=16)),
                ('datos', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_repartidos', to='personas.usuariopos'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('procesado', 'Procesado'), ('cobrar', 'Por cobrar'), ('pagado', 'Pagado'), ('programado', 'Programado'), ('cancelado', 'Cancelado')], default='abierto', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('descuento_porcentaje__gte', 0), ('descuento_porcentaje__lte', 100)), name='ticket_descuento_valido'),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_caja', to='personas.sucursal'),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='tickets',
            field=models.ManyToManyField(related_name='cortes_caja', to='ventas.ticket'),
        ),
        migrations.AddField(
            model_name='cortesucursal',
            name='cliente_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes', to='ventas.sucursalpedido'),
        ),
        migrations.AddField(
            model_name='cortesucursal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_sucursal', to='personas.sucursal'),
        ),
        migrations.AddField(
            model_name='cortesucursal',
            name='tickets',
            field=models.ManyToManyField(related_name='cortes_sucursal', to='ventas.ticket'),
        ),
        migrations.AddField(
            model_name='liquidacionrepartidor',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_repartidor', to='personas.usuariopos'),
        ),
        migrations.AddField(
            model_name='liquidacionrepartidor',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_repartidor', to='personas.sucursal'),
        ),
        migrations.AddField(
            model_name='liquidacionrepartidor',
            name='tickets',
            field=models.ManyToManyField(related_name='liquidaciones_repartidor', to='ventas.ticket'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='personas.sucursal'),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='movimientos',
            field=models.ManyToManyField(related_name='cortes_caja', to='ventas.movimientocaja'),
        ),
        migrations.AddField(
            model_name='reporteadministrativo',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_administrativos', to='personas.sucursal'),
        ),
        migrations.AddField(
            model_name='liquidacionrepartidor',
            name='reporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='liquidacion_repartidor', to='ventas.reporteadministrativo'),
        ),
        migrations.AddField(
            model_name='cortesucursal',
            name='reporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corte_sucursal', to='ventas.reporteadministrativo'),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='reporte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corte_caja', to='ventas.reporteadministrativo'),
        ),
    ]
