# Generated by Django 5.2.17 on 2026-08-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_configuracionsucursal_cortecaja_cortesucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='activado_programado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
