# Generated by Codex on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0013_ticket_activado_programado_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="version_entidad",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ticket",
            name="bloqueo_device_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="ticket",
            name="bloqueo_operador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_en_edicion",
                to="personas.usuariopos",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="bloqueo_tomado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="bloqueo_heartbeat_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="bloqueo_expira_en",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["estado", "bloqueo_expira_en"], name="ventas_t_estado_bloq_idx"),
        ),
    ]
