# Generated by Django 5.2.17 on 2026-09-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_remove_usuariopos_usuario_clave_sucursal_rol_tipo_and_more'),
        ('ventas', '0014_ticket_bloqueo_edicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoFolio',
            fields=[
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='consecutivo_folios', serialize=False, to='personas.sucursal')),
                ('serie', models.PositiveIntegerField(default=1)),
                ('ultimo', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='modificadorticket',
            name='modificador_unico_comensal',
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='ticket_folio_sucursal',
        ),
        migrations.AddField(
            model_name='modificadorticket',
            name='comanda_numero',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partida',
            name='comanda_numero',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comanda_actual',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comanda_en_edicion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contextos_comandas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hora_programada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='serie_folio',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comanda_en_edicion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='modificadorticket',
            constraint=models.UniqueConstraint(fields=('ticket', 'comanda_numero', 'comensal', 'codigo'), name='modificador_unico_comanda_comensal'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('sucursal', 'serie_folio', 'folio'), name='ticket_folio_serie_sucursal'),
        ),
    ]
