# Generated by Django 5.2.17 on 2026-09-17 18:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def normalizar_tipos_movimiento(apps, schema_editor):
    MovimientoCaja = apps.get_model("ventas", "MovimientoCaja")
    MovimientoCaja.objects.filter(tipo="entrada").update(tipo="ingreso")
    MovimientoCaja.objects.filter(tipo="salida").update(tipo="gasto")


def revertir_tipos_movimiento(apps, schema_editor):
    MovimientoCaja = apps.get_model("ventas", "MovimientoCaja")
    MovimientoCaja.objects.filter(tipo="ingreso").update(tipo="entrada")
    MovimientoCaja.objects.filter(tipo="gasto").update(tipo="salida")


def ampliar_posiciones_mostrador(apps, schema_editor):
    Mesa = apps.get_model("ventas", "Mesa")
    Sucursal = apps.get_model("personas", "Sucursal")
    for sucursal in Sucursal.objects.all().iterator():
        for canal, prefijo, etiqueta in (
            ("recoger", "REC", "Recoger"),
            ("llevar", "LLEV", "Llevar"),
        ):
            for numero in range(1, 41):
                Mesa.objects.get_or_create(
                    sucursal_id=sucursal.id,
                    clave=f"{prefijo}-{numero}",
                    defaults={
                        "canal": canal,
                        "nombre": f"{etiqueta} {numero}",
                        "orden": numero,
                        "activa": True,
                    },
                )

class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_producto_imagen'),
        ('personas', '0004_modulos_sucursal'),
        ('ventas', '0016_solicitudrepeticionticket_cortecaja_inicio_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidacionMensual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.DateField(help_text='Primer día del mes consolidado.')),
                ('idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada por VPS'), ('purgada', 'Datos locales eliminados'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('totales', models.JSONField(default=dict)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('acuse_vps', models.CharField(blank=True, max_length=160)),
                ('ultimo_error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('purgado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='ControlEfectivoDia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fondo_anterior', models.JSONField(blank=True, default=dict)),
                ('fondo_siguiente', models.JSONField(blank=True, default=dict)),
                ('ventas_apps', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='partida',
            name='partida_un_solo_catalogo',
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='detalle_eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='total_fondo_anterior',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='total_fondo_siguiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='total_terminales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='totales_sucursales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='ventas_apps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='partida',
            name='personalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_cancelados', to='personas.usuariopos'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cancelado_por_nombre',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.RunPython(
            normalizar_tipos_movimiento,
            revertir_tipos_movimiento,
        ),
        migrations.RunPython(
            ampliar_posiciones_mostrador,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('terminal', 'Terminal')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='partida',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('personalizada', True), ('producto__isnull', True), ('producto_sucursal__isnull', True)), models.Q(('personalizada', False), ('producto__isnull', False), ('producto_sucursal__isnull', True)), models.Q(('personalizada', False), ('producto__isnull', True), ('producto_sucursal__isnull', False)), _connector='OR'), name='partida_origen_valido'),
        ),
        migrations.AddField(
            model_name='consolidacionmensual',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidaciones_mensuales', to='personas.sucursal'),
        ),
        migrations.AddField(
            model_name='controlefectivodia',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_efectivo', to='personas.sucursal'),
        ),
        migrations.AddConstraint(
            model_name='consolidacionmensual',
            constraint=models.UniqueConstraint(fields=('sucursal', 'periodo'), name='consolidacion_periodo_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='controlefectivodia',
            constraint=models.UniqueConstraint(fields=('sucursal', 'fecha'), name='control_efectivo_fecha_sucursal'),
        ),
    ]
