# Generated by Django 5.2.17 on 2026-09-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_usuariopos_es_sistema_and_more'),
        ('ventas', '0019_catalogo_sucursales_unidades_dev9'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSincronizacionPedidos',
            fields=[
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estado_sincronizacion_pedidos', serialize=False, to='personas.sucursal')),
                ('version_api', models.CharField(default='v2', max_length=8)),
                ('estado', models.CharField(choices=[('listo', 'Listo'), ('reconciliacion', 'Requiere conciliacion'), ('contrato_rechazado', 'Contrato rechazado'), ('autenticacion', 'Requiere credencial'), ('error_transitorio', 'Error transitorio'), ('pausado', 'Pausado')], default='listo', max_length=24)),
                ('ventana_desde', models.DateTimeField(blank=True, null=True)),
                ('ventana_hasta', models.DateTimeField(blank=True, null=True)),
                ('sucursales_origen', models.JSONField(blank=True, default=list)),
                ('cursor', models.TextField(blank=True)),
                ('ultimo_cursor_confirmado', models.TextField(blank=True)),
                ('ultimo_request_id', models.CharField(blank=True, max_length=64)),
                ('ultimo_codigo_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detalle_seguro', models.CharField(blank=True, max_length=240)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultima_sincronizacion_en', models.DateTimeField(blank=True, null=True)),
                ('conciliacion_requerida_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='configuracionsucursal',
            name='actor_administrador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracion_como_administrador', to='personas.usuariopos'),
        ),
        migrations.AddField(
            model_name='consolidacionmensual',
            name='estado_vps',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='consolidacionmensual',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='consolidacionmensual',
            name='payload_inmutable',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domiciliocliente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='acuse_remoto',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='destino',
            field=models.CharField(choices=[('local', 'Auditoria local'), ('central_ventas_v2', 'Central: ventas v2'), ('central_clientes_v2', 'Central: clientes v2'), ('central_catalogo_ack_v2', 'Central: ACK catalogo v2')], default='local', max_length=32),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='estado_entrega',
            field=models.CharField(choices=[('local', 'Solo local'), ('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('conciliacion', 'Requiere conciliacion'), ('cuarentena', 'Cuarentena'), ('suspendido', 'Suspendido')], default='local', max_length=16),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='estado_remoto',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='proximo_intento_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='ultima_respuesta_http',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='version_contrato',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventooutbox',
            name='version_origen',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sucursalpedido',
            name='identidad_confirmada_en',
            field=models.DateTimeField(blank=True, help_text='Confirmacion manual del vinculo con SucursalCliente. El nombre remoto nunca confirma la identidad.', null=True),
        ),
        migrations.AddField(
            model_name='telefonocliente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consolidacionmensual',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada por VPS'), ('purgada', 'Datos locales eliminados'), ('error', 'Error'), ('conciliacion', 'Requiere conciliacion')], default='pendiente', max_length=12),
        ),
        migrations.AddIndex(
            model_name='eventooutbox',
            index=models.Index(fields=['destino', 'estado_entrega', 'proximo_intento_en', 'creado_en'], name='ventas_outbox_entrega_idx'),
        ),
    ]
