# Generated by Django 5.2.17 on 2026-09-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_estadosincronizacionpedidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='version_entidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
