# Generated by Django 5.2.17 on 2026-09-24 15:56

from django.db import migrations, models


def congelar_precio_positivo(apps, schema_editor):
    Partida = apps.get_model("ventas", "Partida")
    Partida.objects.filter(
        precio_lista_capturado__isnull=True,
        precio_unitario__gt=0,
    ).update(precio_lista_capturado=models.F("precio_unitario"))


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_configuracionsucursal_instalacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='precio_lista_capturado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(
            congelar_precio_positivo,
            migrations.RunPython.noop,
        ),
    ]
