# Generated by Django 5.2.17 on 2026-09-25 19:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_publicacioncatalogocentral_identidades'),
        ('personas', '0007_production_capacidades_modulos'),
        ('ventas', '0024_checkpoint_pedidos_v2_identidad_durable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinicionPromocion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('central_id', models.UUIDField(blank=True, null=True)),
                ('version_publicacion', models.PositiveIntegerField(default=0)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_semana', models.JSONField(default=list)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('legado', 'Migración local'), ('central', 'Publicación Central')], default='central', max_length=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definiciones_promocion', to='catalogo.producto')),
                ('producto_identidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='definiciones_promocion', to='catalogo.identidadproductocentral')),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='definiciones_promocion', to='catalogo.publicacioncatalogocentral')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definiciones_promocion', to='personas.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='promocion_definicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas_raiz', to='ventas.definicionpromocion'),
        ),
        migrations.CreateModel(
            name='GrupoPromocion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('central_id', models.UUIDField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField()),
                ('cantidad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='ventas.definicionpromocion')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='partida',
            name='promocion_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidas_componente', to='ventas.grupopromocion'),
        ),
        migrations.CreateModel(
            name='ProductoPermitidoPromocion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permitidos', to='ventas.grupopromocion')),
                ('identidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos_promocion', to='catalogo.identidadproductocentral')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos_promocion', to='catalogo.producto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='definicionpromocion',
            constraint=models.UniqueConstraint(condition=models.Q(('origen', 'central')), fields=('sucursal', 'central_id', 'version_publicacion'), name='promo_central_version_unica'),
        ),
        migrations.AddConstraint(
            model_name='definicionpromocion',
            constraint=models.UniqueConstraint(fields=('sucursal', 'producto', 'version_publicacion'), name='promo_producto_version_unica'),
        ),
        migrations.AddConstraint(
            model_name='grupopromocion',
            constraint=models.UniqueConstraint(fields=('definicion', 'orden'), name='promo_grupo_orden_unico'),
        ),
        migrations.AddConstraint(
            model_name='grupopromocion',
            constraint=models.UniqueConstraint(condition=models.Q(('central_id__isnull', False)), fields=('definicion', 'central_id'), name='promo_grupo_central_unico'),
        ),
        migrations.AddConstraint(
            model_name='productopermitidopromocion',
            constraint=models.UniqueConstraint(fields=('grupo', 'producto'), name='promo_grupo_producto_unico'),
        ),
        migrations.AddConstraint(
            model_name='productopermitidopromocion',
            constraint=models.UniqueConstraint(condition=models.Q(('identidad__isnull', False)), fields=('grupo', 'identidad'), name='promo_grupo_identidad_unica'),
        ),
    ]
