# Generated by Django 5.2.17 on 2026-08-15 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoImpresion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formato', models.CharField(choices=[('comanda', 'Comanda'), ('cuenta', 'Cuenta')], max_length=12)),
                ('destino', models.CharField(choices=[('cocina', 'Cocina'), ('barra', 'Barra'), ('caja', 'Caja')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('impreso', 'Impreso'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('archivo', models.CharField(blank=True, max_length=300)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_impresion', to='personas.sucursal')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_impresion', to='ventas.ticket')),
            ],
            options={
                'verbose_name_plural': 'Trabajos de impresión',
                'ordering': ['creado_en'],
                'indexes': [models.Index(fields=['estado', 'creado_en'], name='impresion_t_estado_309b97_idx')],
            },
        ),
    ]
