# Generated by Django 5.2.17 on 2026-08-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajoimpresion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('generado', 'Vista previa generada'), ('impreso', 'Impreso'), ('error', 'Error')], default='pendiente', max_length=12),
        ),
    ]
