# Generated by Django 5.2 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impresion", "0002_alter_trabajoimpresion_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabajoimpresion",
            name="formato",
            field=models.CharField(
                choices=[("comanda", "Comanda"), ("cuenta", "Cuenta"), ("domicilio", "Domicilio")],
                max_length=12,
            ),
        ),
    ]
