# Generated by Django 5.2.17 on 2026-08-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0003_alter_trabajoimpresion_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajoimpresion',
            name='formato',
            field=models.CharField(choices=[('comanda', 'Comanda'), ('cuenta', 'Cuenta'), ('domicilio', 'Domicilio'), ('sucursal', 'Pedido de sucursal')], max_length=12),
        ),
    ]
