# Generated by Django 5.2.17 on 2026-08-29 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0004_alter_trabajoimpresion_formato'),
        ('personas', '0003_remove_usuariopos_usuario_clave_sucursal_rol_tipo_and_more'),
        ('ventas', '0012_configuracionsucursal_cortecaja_cortesucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoimpresion',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_impresion', to='ventas.reporteadministrativo'),
        ),
        migrations.AlterField(
            model_name='trabajoimpresion',
            name='formato',
            field=models.CharField(choices=[('comanda', 'Comanda'), ('cuenta', 'Cuenta'), ('domicilio', 'Domicilio'), ('sucursal', 'Pedido de sucursal'), ('liquidacion', 'Total de repartidor'), ('parcial', 'Reporte parcial'), ('corte_caja', 'Corte de caja'), ('corte_sucursal', 'Corte de sucursal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajoimpresion',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_impresion', to='ventas.ticket'),
        ),
        migrations.AddConstraint(
            model_name='trabajoimpresion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reporte__isnull', True), ('ticket__isnull', False)), models.Q(('reporte__isnull', False), ('ticket__isnull', True)), _connector='OR'), name='impresion_un_documento'),
        ),
    ]
