# Generated by Django 5.2.17 on 2026-09-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0005_trabajoimpresion_reporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoimpresion',
            name='comanda_numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
