# Generated by Django 5.2.17 on 2026-09-24 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0006_trabajoimpresion_comanda_numero'),
        ('personas', '0006_usuariopos_es_sistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoimpresion',
            name='device_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='trabajoimpresion',
            name='origen_ruta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trabajoimpresion',
            name='printer_host',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajoimpresion',
            name='printer_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConfiguracionImpresionTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('host_caja', models.GenericIPAddressField(blank=True, null=True)),
                ('host_cocina', models.GenericIPAddressField(blank=True, null=True)),
                ('host_barra', models.GenericIPAddressField(blank=True, null=True)),
                ('puerto', models.PositiveIntegerField(default=9100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_impresion_terminal', to='personas.sucursal')),
            ],
            options={
                'ordering': ['nombre', 'device_id'],
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'device_id'), name='impresion_terminal_unica_sucursal'), models.CheckConstraint(condition=models.Q(('puerto__gte', 1), ('puerto__lte', 65535)), name='impresion_terminal_puerto_valido')],
            },
        ),
    ]
