# Generated by Django 5.2.17 on 2026-09-25 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresion', '0007_trabajoimpresion_device_id_and_more'),
        ('personas', '0007_production_capacidades_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoimpresion',
            name='printer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajoimpresion',
            name='printer_host',
            field=models.CharField(blank=True, max_length=253, null=True),
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=253)),
                ('puerto', models.PositiveIntegerField(default=9100)),
                ('descripcion', models.CharField(blank=True, max_length=240)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impresoras', to='personas.sucursal')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionImpresoraTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destino', models.CharField(choices=[('todos', 'Todos los trabajos'), ('caja', 'Caja'), ('cocina', 'Cocina'), ('barra', 'Barra')], max_length=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_impresora', to='impresion.configuracionimpresionterminal')),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_terminal', to='impresion.impresora')),
            ],
            options={
                'ordering': ['destino'],
            },
        ),
        migrations.AddConstraint(
            model_name='impresora',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nombre'), name='impresora_nombre_unico_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='impresora',
            constraint=models.CheckConstraint(condition=models.Q(('puerto__gte', 1), ('puerto__lte', 65535)), name='impresora_puerto_valido'),
        ),
        migrations.AddConstraint(
            model_name='asignacionimpresoraterminal',
            constraint=models.UniqueConstraint(fields=('terminal', 'destino'), name='impresora_ruta_unica_terminal'),
        ),
    ]
