# Generated by Django 5.2.17 on 2026-09-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0007_production_capacidades_modulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatidoServicio',
            fields=[
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ultimo_en', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionAccesoEdge',
            fields=[
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='configuracion_acceso_edge', serialize=False, to='personas.sucursal')),
                ('host', models.CharField(blank=True, max_length=253)),
                ('puerto', models.PositiveIntegerField(default=8000)),
                ('usar_https', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('puerto__gte', 1), ('puerto__lte', 65535)), name='soporte_acceso_edge_puerto_valido')],
            },
        ),
    ]
