# Generated by Django 5.2.17 on 2026-09-25 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_production_capacidades_modulos'),
        ('soporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionImpresionFisica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('huella_topologia', models.CharField(max_length=64)),
                ('nota', models.CharField(max_length=240)),
                ('confirmado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_impresion_fisica', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_impresion_fisica', to='personas.sucursal')),
            ],
            options={
                'ordering': ['-confirmado_en'],
            },
        ),
    ]
