# Generated by Django 5.2.17 on 2026-08-29 01:05

from django.db import migrations, models


def migrar_roles_y_claves(apps, schema_editor):
    from django.contrib.auth.hashers import identify_hasher, make_password

    Rol = apps.get_model("personas", "Rol")
    UsuarioPOS = apps.get_model("personas", "UsuarioPOS")
    for rol in Rol.objects.all():
        nombre = rol.nombre.casefold()
        rol.tipo = "repartidor" if "repart" in nombre else "encargado" if "encarg" in nombre else "mesero"
        rol.save(update_fields=["tipo"])
    for usuario in UsuarioPOS.objects.all():
        try:
            identify_hasher(usuario.clave)
            continue
        except ValueError:
            pass
        clave = usuario.clave if len(usuario.clave) == 4 and usuario.clave.isdigit() else "1111"
        usuario.clave = make_password(clave)
        usuario.save(update_fields=["clave"])


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_permisos_y_cuenta_django'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuariopos',
            name='usuario_clave_sucursal',
        ),
        migrations.AddField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('encargado', 'Encargado'), ('mesero', 'Mesero'), ('repartidor', 'Repartidor')], default='mesero', max_length=16),
        ),
        migrations.AlterField(
            model_name='usuariopos',
            name='clave',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(migrar_roles_y_claves, migrations.RunPython.noop),
    ]
