# Generated by Django 5.2.17 on 2026-09-24 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_rol_tipo_elevado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopos',
            name='es_sistema',
            field=models.BooleanField(default=False, help_text='Actor tecnico protegido; no se administra como personal operativo.'),
        ),
        migrations.AddConstraint(
            model_name='usuariopos',
            constraint=models.UniqueConstraint(condition=models.Q(('es_sistema', True)), fields=('sucursal',), name='usuario_sistema_unico_sucursal'),
        ),
    ]
